### ISSUE TITLE
Find a better way to specify mandatory parameters

### ISSUE THREAD

**Issue by stropitek** [image-js/image-js-docs#28]
![CleanShot 2023-09-01 at 11 07 51](https://github.com/image-js/image-js-docs/assets/4118690/277a3294-ed21-44bc-be2f-5ea1b5598b65)

**Comment by stropitek** [comment]
They should be ordered mandatory first, and I think the "mandatory" word can be in the default value column or in a third column (to be tested)

**Comment by targos** [comment]
I prefer "required" instead of "mandatory".
